#!/bin/bash
# setup-expiry.sh — Run ONCE on the client machine after deployment.
#
# Usage:
#   ./scripts/setup-expiry.sh YYYY-MM-DD
#
# What it does:
#   1. Writes a check script to /usr/local/bin/demo-expiry-check.sh
#   2. Installs TWO cron triggers: daily at midnight + on every system boot
#      This ensures expiry fires even if the PC was off when midnight passed.
#
# On expiry date, the cron job:
#   - Stops and removes all containers, Docker images, and volumes
#   - Deletes the entire project directory from disk
#   - Removes itself from crontab and self-deletes
#
# Requires: root or sudo to write to /usr/local/bin

EXPIRY_DATE="$1"
COMPOSE_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [ -z "$EXPIRY_DATE" ]; then
    echo "Usage: $0 YYYY-MM-DD"
    echo "Example: $0 2026-07-15"
    exit 1
fi

# Validate date format
if ! date -d "$EXPIRY_DATE" >/dev/null 2>&1; then
    echo "Error: '$EXPIRY_DATE' is not a valid date. Use YYYY-MM-DD format."
    exit 1
fi

CHECKER="/usr/local/bin/demo-expiry-check.sh"

# Write the nightly destruction script outside the project dir so it
# survives long enough to clean up after deleting the project directory.
cat > "$CHECKER" <<EOF
#!/bin/bash
# Auto-generated by setup-expiry.sh — do not edit
EXPIRY="$EXPIRY_DATE"
TODAY=\$(date +%Y-%m-%d)
LOG=/var/log/demo-expiry.log

if [[ "\$TODAY" > "\$EXPIRY" ]] || [[ "\$TODAY" == "\$EXPIRY" ]]; then
    echo "\$(date): Demo expired on \$EXPIRY. Beginning destruction..." >> \$LOG

    # Stop containers and remove all images + volumes
    cd "$COMPOSE_DIR" && docker compose down --rmi all --volumes --remove-orphans >> \$LOG 2>&1
    echo "\$(date): Docker stack removed." >> \$LOG

    # Delete all project source files
    rm -rf "$COMPOSE_DIR" >> \$LOG 2>&1
    echo "\$(date): Project directory '$COMPOSE_DIR' deleted." >> \$LOG

    # Remove crontab entry and self-delete
    crontab -l 2>/dev/null | grep -v "demo-expiry-check.sh" | crontab -
    rm -f /usr/local/bin/demo-expiry-check.sh
    echo "\$(date): Cleanup complete." >> \$LOG
fi
EOF
chmod +x "$CHECKER"

# Install TWO cron triggers (replace any existing entries):
#   1. Daily at midnight  — fires while PC is running
#   2. On every boot      — fires if the PC was off when midnight passed
(crontab -l 2>/dev/null | grep -v "demo-expiry-check.sh"; \
 echo "0 0 * * * $CHECKER"; \
 echo "@reboot $CHECKER") | crontab -

echo ""
echo "Auto-expiry (full destruction) configured:"
echo "  Expiry date : $EXPIRY_DATE"
echo "  Project dir : $COMPOSE_DIR"
echo "  Check script: $CHECKER"
echo "  Cron        : runs daily at midnight AND on every system boot"
echo ""
echo "On/after $EXPIRY_DATE:"
echo "  - If PC is on at midnight  → destroyed immediately"
echo "  - If PC was off at midnight → destroyed on next boot"
echo "  - All containers, Docker images, volumes, and source files are removed"
echo ""
echo "To verify the cron jobs are installed:"
echo "  crontab -l | grep expiry"
echo ""
echo "WARNING: To test without waiting — edit $CHECKER, set EXPIRY to yesterday, then run: sudo $CHECKER"
